/**
 * generate `index.ts` for icons
 */

const fs = require('fs');
const path = require('path');
const glob = require('glob');
const chalk = require('chalk');
const prettier = require('prettier');

console.log(chalk.blue('generating `index.ts` for icons...'));

/**
 * @param {string[]} filePaths full paths of icons
 * @param {(filename: string) => string} transformer transform filename to icon name
 * @returns {Promise<void>}
 */
function genCodeLines(filePaths, transformer) {
  const lines = [];
  lines.push(`// code generated by \`script:genIconIdx\` - DO NOT EDIT`);

  const genLine = async () => {
    for (const filePath of filePaths) {
      const fullPath = path.resolve(__dirname, '../', filePath);
      const basename = path.basename(fullPath);
      const realname = basename.replace(/\.svg$/, '');
      const exportname = transformer(realname);
      lines.push(
        `export { default as ${exportname} } from './${basename}?react';`
      );
      const prettierOptions = await import('../prettier.config.mjs');
      const code = await prettier.format(lines.join('\n') + '\n', {
        parser: 'typescript',
        ...prettierOptions,
      });
      const idxPath = path.join(path.dirname(fullPath), 'index.ts');
      fs.writeFileSync(idxPath, code, { encoding: 'utf-8' });
    }
  };

  return genLine();
}

const workers = [];
const icons = glob.sync('src/assets/icons/*.svg');
workers.push(
  genCodeLines(icons, (filename) =>
    filename
      .split('-')
      .map((s) => s[0].toUpperCase() + s.slice(1))
      .join('')
  )
);
const jobs = glob.sync('src/assets/jobs/*.svg');
workers.push(genCodeLines(jobs, (filename) => filename.toUpperCase()));

Promise.all(workers)
  .then(() => {
    console.log(
      chalk.green(
        `generated \`index.ts\` for ${icons.length} icons and ${jobs.length} jobs`
      )
    );
    process.exitCode = 0;
  })
  .catch((e) => {
    console.log(chalk.red('failed to generate some of indexes'));
    console.error(e);
    process.exitCode = 1;
  });
