/**
 * generate `index.ts` for icons
 */

import fs from 'fs';
import path from 'path';
import url from 'url';

import chalk from 'chalk';
import * as glob from 'glob';
import { format } from 'oxfmt';

import fmtConfig from '../oxfmt.config';

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log(chalk.blue('generating `index.ts` for icons...'));

function genCodeLines(
  filePaths: string[],
  transformer: (filename: string) => string
): Promise<void> {
  const lines: string[] = [];
  lines.push(`// code generated by \`script:genIconIdx\` - DO NOT EDIT`);

  const genLine = async () => {
    for (const filePath of filePaths) {
      const fullPath = path.resolve(__dirname, '../', filePath);
      const basename = path.basename(fullPath);
      const realname = basename.replace(/\.svg$/, '');
      const exportname = transformer(realname);
      lines.push(`export { default as ${exportname} } from './${basename}?react';`);
      const { code } = await format('index.ts', lines.join('\n') + '\n', fmtConfig);
      const idxPath = path.join(path.dirname(fullPath), 'index.ts');
      fs.writeFileSync(idxPath, code, { encoding: 'utf-8' });
    }
  };

  return genLine();
}

const workers = [];
const icons = glob.sync('src/assets/icons/*.svg');
workers.push(
  genCodeLines(icons, (filename) =>
    filename
      .split('-')
      .map((s) => s[0].toUpperCase() + s.slice(1))
      .join('')
  )
);
const jobs = glob.sync('src/assets/jobs/*.svg');
workers.push(genCodeLines(jobs, (filename) => filename.toUpperCase()));

Promise.all(workers)
  .then(() => {
    console.log(
      chalk.green(`generated \`index.ts\` for ${icons.length} icons and ${jobs.length} jobs`)
    );
    process.exitCode = 0;
  })
  .catch((e) => {
    console.log(chalk.red('failed to generate some of indexes'));
    console.error(e);
    process.exitCode = 1;
  });
